import Navbar from '@/components/Navbar'
import Providers from '@/components/providers'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getTokens } from "next-firebase-auth-edge/lib/next/tokens";
import { cookies } from "next/headers";
import { Tokens } from "next-firebase-auth-edge/lib/auth";
import { UserInfo } from "firebase/auth";
import { ServerAuthProvider } from '@/components/providers/server-auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tracker',
  description: 'Generated by create next app',
}
const mapTokensToUser = ({ decodedToken }: Tokens): UserInfo => {
  const {
    uid,
    email,
    picture: photoURL,
    email_verified: emailVerified,
    phone_number: phoneNumber,
    name: displayName,
  } = decodedToken;

  return {
    uid,
    email: email ?? null,
    displayName: displayName ?? null,
    photoURL: photoURL ?? null,
    phoneNumber: phoneNumber ?? null,
    // @ts-ignore
    emailVerified: emailVerified ?? false,
    provider: "firebase",
  };
};

export default async function RootLayout({
  children,
  authModal
}: {
  children: React.ReactNode
  authModal: React.ReactNode
}) {

  return (

    <html lang="en">
      <body className={`${inter.className} ${process.env.NODE_ENV !== "production" && "debug-screens"}`}>
        <ServerAuthProvider>

          <Providers>


            <Navbar />
            {authModal}
            {children}

          </Providers>
        </ServerAuthProvider>

      </body>
    </html>
  )
}


